{% set version = "0.22" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pagedown
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pagedown_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pagedown/pagedown_{{ version }}.tar.gz
  sha256: 5fb12d8518649496ea241aec6e902f2b1cad8b5917c6457bc923d7bd06d67244

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bookdown >=0.8
    - r-htmltools
    - r-httpuv
    - r-jsonlite
    - r-later >=1.0.0
    - r-processx
    - r-rmarkdown >=2.8
    - r-servr >=0.23
    - r-websocket
    - r-xfun
    - pandoc >=2.2.3
  run:
    - r-base
    - r-bookdown >=0.8
    - r-htmltools
    - r-httpuv
    - r-jsonlite
    - r-later >=1.0.0
    - r-processx
    - r-rmarkdown >=2.8
    - r-servr >=0.23
    - r-websocket
    - r-xfun
    - pandoc >=2.2.3

test:
  commands:
    - $R -e "library('pagedown')"           # [not win]
    - "\"%R%\" -e \"library('pagedown')\""  # [win]

about:
  home: https://github.com/rstudio/pagedown
  license: MIT
  summary: Use the paged media properties in CSS and the JavaScript library 'paged.js' to split the content of an HTML document into discrete pages. Each page can have its page size, page numbers, margin boxes, and running headers, etc. Applications of this package include books, letters, reports, papers, business cards,
    resumes, and posters.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
